name: Deploy Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: '24'
        cache: 'npm'
    - run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.READ_PACKAGE_TOKEN }}
        CI: true
    - name: Deploy docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./deploy.sh
